### ISSUE TITLE
Question about examples

### ISSUE THREAD

**Issue by paf31** [purescript-contrib/purescript-ace#1]
The spec states that "all bound functions are exercised in the examples, to ensure the bindings and necessary wrapping, unwrapping, encoding, and decoding has been performed correctly".

My current bindings contain 942 exported functions. Creating a demo for each of these is going to be a massive task - can we simplify this requirement a little?

If ensuring the bindings are correct is the main goal, then I can simply call each one in turn with dummy arguments, but it would be part of a test suite, not necessarily the examples. I also already have a bit more confidence in the correctnesss of my bindings since they're based on an existing set of bindings for TypeScript.

**Comment by jdegoes** [comment]
Yes, simply calling each one and ensuring no exceptions are thrown (e.g. in a test suite) would be fine. It's just to provide a semi-easy method of making sure the bindings were defined correctly.

**Comment by jdegoes** [comment]
^^^ Also let me know if the above is too onerous.

**Comment by paf31** [comment]
Sounds good.

The TypeScript definition files contain some things which are not documented in the API docs, which I have been removing, and some things which use things like union types or `any`, so I need to spend a little more time to get working examples for those, but I'm almost done.

**Comment by jdegoes** [comment]
Awesome, look forward to seeing it.
